# Generated by Django 5.2.6 on 2026-01-29 13:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="greenaction",
            options={"ordering": ["category", "title"]},
        ),
        migrations.RemoveField(
            model_name="greenaction",
            name="co2_saved",
        ),
        migrations.RemoveField(
            model_name="greenaction",
            name="points",
        ),
        migrations.AddField(
            model_name="greenaction",
            name="co2_per_unit",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="greenaction",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="greenaction",
            name="points_per_unit",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="greenaction",
            name="slug",
            field=models.SlugField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="greenaction",
            name="unit",
            field=models.CharField(default="times", max_length=50),
        ),
        migrations.AddField(
            model_name="greenaction",
            name="water_per_unit",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="useractivity",
            name="activity_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="useractivity",
            name="activity_name",
            field=models.CharField(default="Green Activity", max_length=200),
        ),
        migrations.AddField(
            model_name="useractivity",
            name="activity_subtype",
            field=models.CharField(default="other", max_length=100),
        ),
        migrations.AddField(
            model_name="useractivity",
            name="activity_type",
            field=models.CharField(default="other", max_length=100),
        ),
        migrations.AddField(
            model_name="useractivity",
            name="unit",
            field=models.CharField(default="times", max_length=50),
        ),
        migrations.AddField(
            model_name="useractivity",
            name="water_saved",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="greenaction",
            name="category",
            field=models.CharField(
                choices=[
                    ("transport", "Transportation"),
                    ("electricity", "Energy Saving"),
                    ("recycling", "Recycling & Waste"),
                    ("water", "Water Conservation"),
                    ("food", "Sustainable Food"),
                    ("other", "Other Activities"),
                ],
                default="other",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="greenaction",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="useractivity",
            name="action",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.greenaction",
            ),
        ),
        migrations.AlterField(
            model_name="useractivity",
            name="quantity",
            field=models.FloatField(default=1),
        ),
    ]
