# Generated by Django 5.2.6 on 2026-01-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_greenaction_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useractivity",
            name="activity_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
