# Generated by Django 5.2.6 on 2026-01-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_useractivity_activity_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useractivity",
            name="activity_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
